### ISSUE TITLE
どんなゲームを作るのかが分からない

### ISSUE THREAD

**Issue by ghost** [TomyJPN/UnityBook#1]
https://github.com/TomyJPN/UnityBook/blob/8ecf35c3dce531ef501178791ce1926891c94d1f/rv_unity/rv_unity.re#L31-L32

まずは全体の見通しをはっきりとさせた方が良いと思う。「佐賀駅を舞台にしたゾンビFPSを作ります」程度でもいいのでさらっと。

**Comment by TomyJPN** [comment]
ありがとうございます！説明を追加しました．
